name: Build and Release V2
permissions:
  contents: write
on:
  workflow_dispatch:
#  push:
#    tags:
#      - "test"

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      # For VyOS 1.2 (crux) use vyos/vyos-build:crux
      # For VyOS 1.3 (equuleus) use vyos/vyos-build:equuleus
      # For our VyOS rolling release you should use vyos/vyos-build which will always refer to the latest image.
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      # echo "RELEASE_VERSION=1.4.0-sv-dae-fullconenat" >> $GITHUB_ENV 
      #   
      # --version 1.4.0-sv-fullconenat  iso
      # 

      image: vyos/vyos-build:current
      env:
        TZ: Asia/Shanghai
      options: --privileged
      

    steps:
    - name: Set env
      run: |
           echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
    - name: git clone vyos-build
      run: |
        set -eux
        
        git clone -b current --single-branch https://github.com/vyos/vyos-build
    
      
    - name: Download deb package 
      run:  |
         set -eux
         cd vyos-build
         wget -P  packages/ http://http.us.debian.org/debian/pool/main/i/ipset/libipset13_7.17-1_amd64.deb
         wget -P  packages/ http://http.us.debian.org/debian/pool/main/i/ipset/ipset_7.17-1_amd64.deb
         wget -P  packages/ http://hnd2.rs4.us/1.4/iptables_1.8.9-2_amd64.deb
         wget -P  packages/ http://hnd2.rs4.us/1.4/libip4tc2_1.8.9-2_amd64.deb 
         wget -P  packages/ http://hnd2.rs4.us/1.4/libip6tc2_1.8.9-2_amd64.deb
         wget -P  packages/ http://hnd2.rs4.us/1.4/libiptc0_1.8.9-2_amd64.deb
         wget -P  packages/ http://hnd2.rs4.us/1.4/libxtables12_1.8.9-2_amd64.deb
         # wget -P  packages/ http://hnd2.rs4.us/1.4/vyos-intel-qat_1.7.L.4.20.0-00001-0_amd64.deb
    - name: Download kernel deb from my another repo
      uses: robinraju/release-downloader@v1.7
      with:
       repository: "debiansid/vyos-kernel-eBPF-fullconenat"
       latest: true
       fileName: "*.deb"
       out-file-path: "vyos-build/packages/"
    
#    - name: build kernel
#      run:  |
#        set -eux
#        pwd
#        cd vyos-build/packages/linux-kernel
#        wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.1.8.tar.xz
#        tar xf linux-6.1.8.tar.xz
#        ln -s linux-6.1.8 linux
#        ./build-kernel.sh
#        cp *.deb ../
        
#    - name: make deb
#      run: |
#        set -eux
#        pwd
#        cd vyos-build/packages/linux-kernel
#        ./build-intel-qat.sh
#        cp vyos-intel-qat*.deb ../
    
#    - name: make iptables deb
#      run: |
#        set -eux 
#        pwd
#        sudo apt-get --install-recommends install libmnl-dev libnetfilter-conntrack-dev libnetfilter-conntrack3 libnfnetlink-dev libnftnl-dev libnfnetlink0 libnftnl11
#        cd vyos-build/packages/iptables
#        ./build.sh
#        rm  *dev*.deb
#        cd *.deb ../
        
    - name: make iso
      working-directory: vyos-build
      run: |
        sudo --preserve-env ./build-vyos-image \
                            --build-by gpt@openai.com \
                            --build-type release \
                            --custom-package prometheus-node-exporter \
                            --version ${{ env.RELEASE_VERSION }} iso
                            
          

    - name: ls
      run: |
        set -eux

        pwd
        ls -lah
        ls -lah vyos-build/build

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ github.ref_name }}
          files: vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso
          body: |
            VyOS ${{ env.RELEASE_VERSION }} LTS
          draft: true
          prerelease: true
          
