name: VyOS SV Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      # For VyOS 1.2 (crux) use vyos/vyos-build:crux
      # For VyOS 1.3 (equuleus) use vyos/vyos-build:equuleus
      # For our VyOS rolling release you should use vyos/vyos-build which will always refer to the latest image.
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:current
      env:
        TZ: Asia/Shanghai
      options: --privileged
      

    steps:
    - name: Set env
      run: |
        echo "RELEASE_VERSION=1.4.0" >> $GITHUB_ENV 

    - name: git clone vyos-build
      run: |
        set -eux
        
        git clone  https://github.com/debiansid/vyos-build-dae-fullconenat vyos-build

    
      
     - name: Download the file
       uses: suisei-cn/actions-download-file@v1.3.0
       with:
       url: "http://hnd2.rs4.us/ipset_7.10-1_amd64.deb"
       url: "http://hnd2.rs4.us/iptables_1.8.7-1_amd64.deb"
       url: "http://hnd2.rs4.us/libip4tc2_1.8.7-1_amd64.deb"
       url: "http://hnd2.rs4.us/libip6tc2_1.8.7-1_amd64.deb"
       url: "http://hnd2.rs4.us/libipset13_7.10-1_amd64.deb"
       url: "http://hnd2.rs4.us/libiptc0_1.8.7-1_amd64.deb"
       url: "http://hnd2.rs4.us/libxtables12_1.8.7-1_amd64.deb"
       target: packages/


    - name: make iso
      working-directory: vyos-build
      run: |
        set -eux
        
        sudo ./build-vyos-image \
        --architecture amd64 \
        --build-by naa0yama@aoya6i.com \
        --build-type release \
        --version ${{ env.RELEASE_VERSION }} iso


    - name: ls
      run: |
        set -eux

        pwd
        ls -lah
        ls -lah vyos-build/build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with: 
          name: vyos-${{ env.RELEASE_VERSION }}-amd64.iso
          path: vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso
