name: VyOS 1.4 sv fullconenat Build and Release
permissions:
  contents: write
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      # For VyOS 1.2 (crux) use vyos/vyos-build:crux
      # For VyOS 1.3 (equuleus) use vyos/vyos-build:equuleus
      # For our VyOS rolling release you should use vyos/vyos-build which will always refer to the latest image.
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:current
      env:
        TZ: Asia/Shanghai
      options: --privileged
      

    steps:
    - name: Set env
      run: |
        echo "RELEASE_VERSION=1.4.0-sv-fullconenat" >> $GITHUB_ENV 

    - name: git clone vyos-build
      run: |
        set -eux
        
        git clone  -b dev-next https://github.com/debiansid/vyos-build-sv-fullconenat vyos-build

    
      
    - name: Download deb from my server
      run:  |
         set -eux
         cd vyos-build
         wget -P  packages/ http://hnd2.rs4.us/1.4/ipset_7.10-1_amd64.deb 
         wget -P  packages/ http://hnd2.rs4.us/1.4/iptables_1.8.7-1_amd64.deb
         wget -P  packages/ http://hnd2.rs4.us/1.4/libip4tc2_1.8.7-1_amd64.deb 
         wget -P  packages/ http://hnd2.rs4.us/1.4/libip6tc2_1.8.7-1_amd64.deb
         wget -P  packages/ http://hnd2.rs4.us/1.4/libipset13_7.10-1_amd64.deb
         wget -P  packages/ http://hnd2.rs4.us/1.4/libiptc0_1.8.7-1_amd64.deb
         wget -P  packages/ http://hnd2.rs4.us/1.4/libxtables12_1.8.7-1_amd64.deb
         wget -P  packages/ http://hnd2.rs4.us/1.4/linux-headers-6.1.8-amd64-vyos_6.1.8-1_amd64.deb 
         wget -P  packages/ http://hnd2.rs4.us/1.4/linux-image-6.1.8-amd64-vyos_6.1.8-1_amd64.deb
         wget -P  packages/ http://hnd2.rs4.us/1.4/linux-tools-6.1.8-amd64-vyos_6.1.8-1_amd64.deb
         wget -P  packages/ http://hnd2.rs4.us/1.4/vyos-intel-qat_1.7.L.4.20.0-00001-0_amd64.deb
         
# wget -P  packages/ http://hnd2.rs4.us/1.4/linux-libc-dev_6.1.8-1_amd64.deb

    - name: make iso
      working-directory: vyos-build
      run: |
        sudo --preserve-env ./build-vyos-image \
                            --build-by gpt@openai.com \
                            --build-type release \
                            --custom-package prometheus-node-exporter \
                            --version 1.4.0-sv-fullconenat  iso


    - name: ls
      run: |
        set -eux

        pwd
        ls -lah
        ls -lah vyos-build/build

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ github.ref_name }}
          files: vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso
          body: |
            VyOS ${{ env.RELEASE_VERSION }} LTS
          draft: true
          prerelease: true
          

